TLS1.3: in DeriveKey bail out if the hash algorithm is not supported
By initializing ret to -1 we give the DeriveKey function a chance to
bail out when the hash algorithm is none of the supported ones.

This issue was found thanks to GCC reporting the following:

In function ‘DeriveKey’,
    inlined from ‘DeriveTrafficSecret’ at src/tls13.c:902:12,
    inlined from ‘DeriveTls13Keys’ at src/tls13.c:1201:23:
src/tls13.c:438:12: error: ‘hash’ may be used uninitialized [-Werror=maybe-uninitialized]
  438 |     return HKDF_Expand_Label(output, outputLen, secret, hashSz,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  439 |                              protocol, protocolLen, label, labelLen,
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  440 |                              hash, hashOutSz, digestAlg);
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/tls13.c: In function ‘DeriveTls13Keys’:
src/tls13.c:224:12: note: by argument 7 of type ‘const byte *’ {aka ‘const unsigned char *’} to ‘HKDF_Expand_Label.constprop’ declared here
  224 | static int HKDF_Expand_Label(byte* okm, word32 okmLen,
      |            ^~~~~~~~~~~~~~~~~
src/tls13.c:388:17: note: ‘hash’ declared here
  388 |     byte        hash[WC_MAX_DIGEST_SIZE];
      |                 ^~~~

Signed-off-by: Antonio Quartulli <a@unstable.cc>